### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Enchufa2** [hypertidy/vapour#95]
```${CXXFLAGS=`"${RBIN}" CMD config CXXFLAGS`}``` is missing in `configure.ac`, and compilation fails on Fedora. See https://download.copr.fedorainfracloud.org/results/iucar/cran/fedora-rawhide-x86_64/01694269-R-CRAN-vapour/builder-live.log.gz

**Comment by mdsumner** [comment]
thanks!   Hopefully fixed now (there are other open issues around recent changes preventing a full check atm)

**Comment by Enchufa2** [comment]
Thanks, this fixes the issue.

**Comment by Enchufa2** [comment]
Kind reminder that Fedora users still cannot install this package from CRAN due to this.

**Comment by Enchufa2** [comment]
Any plan on making a new release with this fix?

**Comment by mdsumner** [comment]
ah yes, I'm quite keen to get some new features out, I'll try soon - thanks

**Comment by mdsumner** [comment]
0.6.5 made it onto CRAN, thanks!
